insert into physicians values ('11', 'Ahmad', 'Ahmadi', '11', 'special', 'nothing', 'general', '2000-11-10', 30, 'M', 20, false)
insert into users values ('ahmad', '1', 'physicians', '11')
insert into physicians values ('12', 'Ali', 'Alavi', '12', 'special', 'section_manager', 'general', '2000-11-10', 30, 'M', 20, false)
insert into users values ('ali', '1', 'physicians', '12')
insert into physicians values ('13', 'Arsalan', 'Arsalani', '31', 'special', 'nothing', 'speciality', '2000-11-10', 30, 'M', 20, false)
insert into users values ('arsalan', '1', 'physicians', '13')
insert into physicians values ('14', 'Arghavan', 'Arghavani', '14', 'special', 'nothing', 'super_speciality', '2000-11-10', 30, 'F', 20, false)
insert into users values ('arghavan', '1', 'physicians', '14')
insert into physicians values ('15', 'Amin', 'Amini', '15', 'special', 'nothing', 'emergency', '2000-11-10', 30, 'M', 20, false)
insert into users values ('amin', '1', 'physicians', '15')
insert into physicians values ('16', 'Abbas', 'Abbasi', '16', 'special', 'nothing', 'emergency', '2000-11-10', 30, 'M', 20, false)
insert into users values ('abbas', '1', 'physicians', '16')
insert into physicians values ('17', 'Amir', 'Amiri', '17', 'special', 'hospital_manager', 'hospital', '2000-11-10', 30, 'M', 20, false)
insert into users values ('amir', '1', 'physicians', '17')
insert into physicians values ('18', 'Asghar', 'Asghari', '18', 'special', 'medical_vp', 'medical', '2000-11-10', 30, 'M', 20, false)
insert into users values ('asghar', '1', 'physicians', '18')
insert into physicians values ('19', 'Akbar', 'Akbari', '19', 'special', 'financial_vp', 'financial', '2000-11-10', 30, 'M', 20, false)
insert into users values ('akbar', '1', 'physicians', '19')
insert into physicians values ('110', 'Arezoo', 'Arezooei', '110', 'special', 'administrative_vp', 'administrative', '2000-11-10', 30, 'M', 20, false)
insert into users values ('arezoo', '1', 'physicians', '110')

insert into nurses values ('21', 'Babak', 'Babaki', '21', 'general', '2000/11/10', 30, 'M', 20, true)
insert into users values ('babak', '1', 'nurses', '21')
insert into nurses values ('22', 'Baran', 'Barani', '22', 'speciality', '2000/11/10', 30, 'F', 20, false)
insert into users values ('baran', '1', 'nurses', '22')
insert into nurses values ('23', 'Behnam', 'Behnami', '23', 'super_speciality', '2000/11/10', 30, 'M', 20, false)
insert into users values ('behnam', '1', 'nurses', '23')
insert into nurses values ('24', 'Behzad', 'Behzadi', '24', 'emergency', '2000/11/10', 30, 'M', 20, false)
insert into users values ('behzad', '1', 'nurses', '24')

insert into employees values ('31', 'Majid', 'Majidi', '31', 'ordinary', 'financial', '2000/11/10', 30, 'M', 20, false)
insert into users values ('majid', '1', 'employees', '31')
insert into employees values ('32', 'Mitra', 'Mitraei', '32', 'ordinary', 'administrative', '2000/11/10', 30, 'F', 20, false)
insert into users values ('mitra', '1', 'employees', '32')
insert into employees values ('33', 'Inspector', 'Gadget', '33', 'inspector', 'hospital', '2000/11/10', 30, 'M', 20, false)
insert into users values ('gadget', '1', 'employees', '33')

insert into patients values ('41', 'Rasool', 'Rasooli', '41', 70, 'M', 'bimar', 'general', '11', '21', 'morphine')
insert into users values ('rasool', '1', 'patients', '41')
insert into patients values ('42', 'Ramin', 'Ramini', '42', 70, 'M', 'bimar', 'general', '12', '21', 'morphine')
insert into users values ('ramin', '1', 'patients', '42')
insert into patients values ('43', 'Rana', 'Ranai', '43', 70, 'F', 'bimar', 'speciality', '13', '22', 'morphine')
insert into users values ('rana', '1', 'patients', '43')
insert into patients values ('44', 'Reza', 'Razavi', '44', 70, 'M', 'bimar', 'super_speciality', '14', '23', 'morphine')
insert into users values ('reza', '1', 'patients', '44')
insert into patients values ('45', 'Reyhane', 'Reyhanei', '45', 70, 'F', 'bimar', 'emergency', '15', '24', 'morphine')
insert into users values ('reyhane', '1', 'patients', '45')
insert into patients values ('46', 'Rahim', 'Rahimi', '46', 70, 'M', 'bimar', 'emergency', '16', '24', 'morphine')
insert into users values ('rahim', '1', 'patients', '46')
